"use client";

import { notFound, useParams } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, BookOpen, Check, History, MessageSquare, Send } from "lucide-react";
import { CoachLayout } from "@/components/coach/CoachLayout";
import { DetailHeader, ScoreBar, SectionHeading } from "@/components/coach/CoachUi";
import { getCoachParticipant } from "@/lib/coach-mock-data";

const checkpointStyles = { ON_TRACK: "bg-emerald-50 text-emerald-700", NEED_SUPPORT: "bg-amber-50 text-amber-800", NOT_FILLED: "bg-slate-100 text-slate-500" };

export default function CoachParticipantDetailPage() {
  const { id } = useParams<{ id: string }>();
  const participant = getCoachParticipant(id);
  const [note, setNote] = useState("");
  const [sent, setSent] = useState(false);
  if (!participant) notFound();

  const sendMockNote = () => { if (!note.trim()) return; setSent(true); setNote(""); setTimeout(() => setSent(false), 3000); };

  return (
    <CoachLayout pageTitle="Detail Peserta" backHref="/coach">
      <DetailHeader participant={participant} />

      <div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div className="min-w-0 space-y-9">
          <section className="space-y-5"><SectionHeading title="Ringkasan PTP" description="Arah perubahan yang disepakati peserta untuk perjalanan 90 hari." action={<Link href={`/coach/participants/${participant.id}/history`} className="inline-flex items-center gap-2 text-xs font-bold text-[#9A762C] hover:text-[#0F1E3D]"><History className="h-4 w-4" />Lihat riwayat</Link>} /><div className="grid gap-px overflow-hidden rounded-xl bg-[#E5E7EB] ring-1 ring-[#E5E7EB] md:grid-cols-2"><div className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Muhasabah</p><p className="mt-3 text-sm leading-relaxed text-slate-700">{participant.muhasabah}</p></div><div className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Niat perubahan</p><p className="mt-3 text-sm font-semibold leading-relaxed text-[#0F1E3D]">{participant.niat}</p></div><div className="bg-white p-5 md:col-span-2"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Target utama</p><p className="mt-3 text-base font-bold leading-relaxed text-[#0F1E3D]">{participant.mainTarget}</p><div className="mt-4 flex flex-wrap gap-2">{participant.transformationAreas.map((area) => <span key={area} className="rounded-full bg-[#FAF8F4] px-3 py-1.5 text-[10px] font-bold text-slate-600 ring-1 ring-[#E5E7EB]">{area}</span>)}</div></div></div></section>

          <section className="space-y-5"><SectionHeading title="Skor Baseline" description="Titik awal lima area pertumbuhan. Skala 0–100." /><div className="space-y-4 rounded-xl bg-white p-5 ring-1 ring-[#E5E7EB] sm:p-6">{Object.entries(participant.baseline).map(([label, value]) => <ScoreBar key={label} label={label} value={value} />)}</div></section>

          <section className="space-y-5"><SectionHeading title="Ritme Habit" description="Completion tujuh hari terakhir dan konsistensi yang sedang terbentuk." /><div className="rounded-xl bg-white p-5 ring-1 ring-[#E5E7EB]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-4xl font-black tracking-tight text-[#0F1E3D]">{participant.habitCompletionPercent}%</p><p className="mt-1 text-xs text-slate-500">Completion rate · streak {participant.streak} hari</p></div><div className="flex h-24 flex-1 items-end gap-2 sm:max-w-md">{participant.habitTrend.map((value, index) => <div key={index} className="flex h-full flex-1 items-end"><div title={`${value}%`} className="w-full rounded-t-sm bg-[#C79A3C] opacity-80" style={{ height: `${Math.max(value, 4)}%` }} /></div>)}</div></div></div></section>

          <section className="space-y-5"><SectionHeading title="Checkpoint & Catatan Coach" description="Tiga checkpoint ditampilkan terpisah agar feedback selalu masuk ke bulan yang tepat." /><div className="grid gap-4 lg:grid-cols-3">{participant.checkpoints.map((checkpoint) => <div key={checkpoint.month} className="rounded-xl bg-white p-5 ring-1 ring-[#E5E7EB]"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Bulan {checkpoint.month}</p><p className="mt-1 text-xs text-slate-500">{checkpoint.date || "Belum dibuka"}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${checkpointStyles[checkpoint.status]}`}>{checkpoint.status === "ON_TRACK" ? "On track" : checkpoint.status === "NEED_SUPPORT" ? "Butuh dukungan" : "Belum diisi"}</span></div><div className="mt-5 border-t border-[#E5E7EB] pt-4"><p className="text-[10px] font-bold text-slate-400">CATATAN PESERTA</p><p className="mt-2 text-xs leading-relaxed text-slate-600">{checkpoint.participantNote || "Belum ada catatan."}</p>{checkpoint.coachNote && <><p className="mt-4 text-[10px] font-bold text-[#9A762C]">RESPONS COACH</p><p className="mt-2 text-xs leading-relaxed text-[#0F1E3D]">{checkpoint.coachNote}</p></>}</div></div>)}</div></section>

          <section className="space-y-5"><SectionHeading title="Laporan Indikator Bulanan" description="Kualitas, kuantitas, waktu, dan biaya per area transformasi." /><div className="overflow-x-auto rounded-xl bg-white ring-1 ring-[#E5E7EB]"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Bulan / Area</th><th className="px-4 py-3">Kualitas</th><th className="px-4 py-3">Kuantitas</th><th className="px-4 py-3">Waktu</th><th className="px-4 py-3">Biaya</th></tr></thead><tbody>{participant.indicatorReports.length ? participant.indicatorReports.map((report, index) => <tr key={`${report.month}-${report.area}-${index}`} className="border-t border-[#E5E7EB]"><td className="px-5 py-4"><p className="font-bold text-[#0F1E3D]">{report.area}</p><p className="mt-0.5 text-[10px] text-slate-400">Bulan {report.month}</p></td>{[report.quality, report.quantity, report.time, report.cost].map((value, valueIndex) => <td key={valueIndex} className="px-4 py-4 font-bold tabular-nums text-slate-700">{value}</td>)}</tr>) : <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">Belum ada laporan indikator.</td></tr>}</tbody></table></div></section>

          <section className="space-y-5"><SectionHeading title="Evaluasi Atasan" description="Penilaian read-only dari atasan peserta." /><div className="grid gap-4 md:grid-cols-2">{participant.managerEvaluations.length ? participant.managerEvaluations.map((evaluation) => <div key={evaluation.month} className="rounded-xl bg-white p-5 ring-1 ring-[#E5E7EB]"><p className="text-xs font-bold text-[#0F1E3D]">Evaluasi Bulan {evaluation.month}</p><div className="mt-4 grid grid-cols-3 gap-3">{[["Produktivitas", evaluation.productivity], ["Disiplin", evaluation.discipline], ["Integritas", evaluation.integrity]].map(([label, value]) => <div key={String(label)} className="bg-[#FAF8F4] p-3 text-center"><p className="text-lg font-black text-[#0F1E3D]">{value}<span className="text-[10px] text-slate-400">/10</span></p><p className="mt-1 text-[9px] font-semibold text-slate-500">{label}</p></div>)}</div><p className="mt-4 border-t border-[#E5E7EB] pt-4 text-xs leading-relaxed text-slate-600">{evaluation.note}</p></div>) : <div className="rounded-xl bg-white p-8 text-center text-xs text-slate-500 ring-1 ring-[#E5E7EB] md:col-span-2">Evaluasi atasan belum tersedia.</div>}</div></section>

          <section className="space-y-5"><SectionHeading title="Jurnal Dibagikan" description="Hanya jurnal yang dipilih peserta untuk dibagikan kepada coach." /><div className="divide-y divide-[#E5E7EB] rounded-xl bg-white ring-1 ring-[#E5E7EB]">{participant.journals.length ? participant.journals.map((journal) => <article key={`${journal.date}-${journal.title}`} className="p-5"><div className="flex items-start gap-3"><BookOpen className="mt-0.5 h-4 w-4 shrink-0 text-[#C79A3C]" /><div><p className="text-[10px] font-semibold text-slate-400">{journal.date}</p><h3 className="mt-1 text-sm font-bold text-[#0F1E3D]">{journal.title}</h3><p className="mt-2 text-xs leading-relaxed text-slate-600">{journal.excerpt}</p></div></div></article>) : <div className="p-8 text-center text-xs text-slate-500">Belum ada jurnal yang dibagikan.</div>}</div></section>
        </div>

        <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start">
          <div className="rounded-xl bg-[#0F1E3D] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-amber-300">Indikator keberhasilan</p><div className="mt-4 space-y-3">{participant.successIndicators.map((indicator) => <div key={indicator} className="flex items-start gap-2.5"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-300" /><p className="text-xs leading-relaxed text-slate-200">{indicator}</p></div>)}</div></div>
          <div className="rounded-xl bg-white p-5 ring-1 ring-[#E5E7EB]"><div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-[#C79A3C]" /><h2 className="text-sm font-bold text-[#0F1E3D]">Catatan pendampingan</h2></div><p className="mt-2 text-[11px] leading-relaxed text-slate-500">Simulasi MVP. Catatan belum disimpan ke database.</p>{sent && <div className="mt-4 bg-emerald-50 p-3 text-xs font-semibold text-emerald-700">Catatan simulasi berhasil dikirim.</div>}<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={5} placeholder="Tulis apresiasi, pertanyaan reflektif, atau arahan berikutnya..." className="mt-4 w-full resize-none rounded-lg border border-[#E5E7EB] p-3 text-xs leading-relaxed outline-none focus:border-[#C79A3C]" /><button onClick={sendMockNote} disabled={!note.trim()} className="mt-3 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#0F1E3D] text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Kirim catatan<Send className="h-3.5 w-3.5" /></button></div>
          <Link href={`/coach/participants/${participant.id}/history`} className="group flex min-h-12 items-center justify-between rounded-xl bg-white px-5 text-xs font-bold text-[#0F1E3D] ring-1 ring-[#E5E7EB] hover:bg-slate-50"><span>Riwayat lengkap peserta</span><ArrowRight className="h-4 w-4 text-[#C79A3C] transition-transform group-hover:translate-x-0.5" /></Link>
        </aside>
      </div>
    </CoachLayout>
  );
}
