import { BookOpenCheck, Check, ChevronRight, Info } from "lucide-react";
import { assessmentDimensions, coachAssessmentRubric, METHODOLOGY_VERSION } from "@/lib/assessment-methodology";

const sections = [
  ["overview", "Ringkasan"], ["model", "Model Penilaian"], ["self-discovery", "Baseline & Endline"], ["ptp", "Struktur PTP"], ["outcome", "Outcome Attainment"], ["execution", "Behavior Execution"], ["engagement", "Program Engagement"], ["coach", "Validasi Coach/Manager"], ["support", "Sahabat Safar"], ["kirkpatrick", "Kirkpatrick"], ["business", "Business Impact & ROI"], ["readiness", "Readiness Index"], ["report", "Group Impact Report"], ["interpretation", "Interpretasi"],
];

function Formula({ children }: { children: React.ReactNode }) {
  return <pre className="my-4 overflow-x-auto rounded-md border border-slate-200 bg-slate-50 p-4 text-xs leading-6 text-[#0F1E3D]"><code>{children}</code></pre>;
}

function Note({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="my-5 border-l-4 border-blue-500 bg-blue-50 p-4"><div className="flex gap-3"><Info className="mt-0.5 h-4 w-4 shrink-0 text-blue-700" /><div><p className="text-sm font-bold text-blue-900">{title}</p><div className="mt-1 text-sm leading-6 text-blue-800">{children}</div></div></div></div>;
}

export default function AdminDocumentationPage() {
  return (
    <div className="mx-auto max-w-[1280px]">
      <div className="border-b border-slate-200 pb-6"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><BookOpenCheck className="h-4 w-4" />Documentation<ChevronRight className="h-3 w-3" />Assessment System</div><h1 className="mt-3 text-3xl font-bold tracking-tight text-[#0F1E3D]">Perhitungan dan Penilaian Dampak SLJ</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">Spesifikasi metodologi untuk menghitung hasil transformasi, pelaksanaan action plan, partisipasi program, dukungan Sahabat Safar, dan validasi multi-sumber.</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span><b className="text-slate-700">Version:</b> {METHODOLOGY_VERSION}</span><span><b className="text-slate-700">Owner:</b> BinaJourney Program Team</span></div></div>

      <div className="grid gap-10 py-8 lg:grid-cols-[220px_minmax(0,760px)_1fr]">
        <aside className="hidden lg:block"><nav className="sticky top-24 border-l border-slate-200 text-sm">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="block border-l-2 border-transparent py-2 pl-4 text-slate-500 hover:border-[#C79A3C] hover:text-[#0F1E3D]">{label}</a>)}</nav></aside>

        <article className="min-w-0 space-y-12 text-sm leading-7 text-slate-700">
          <section id="overview" className="scroll-mt-24"><h2 className="text-2xl font-bold tracking-tight text-[#0F1E3D]">Ringkasan</h2><p className="mt-4">Sistem memisahkan hasil perubahan dari aktivitas yang dilakukan agar setiap skor memiliki definisi, sumber data, dan fungsi yang jelas. Outcome mengukur pencapaian target, sedangkan execution mengukur konsistensi pelaksanaan action plan.</p><Note title="Sumber kebenaran utama">Dokumen kanonik metodologi adalah <code>ASSESSMENT_SYSTEM_SPECIFICATION.md</code> di root repository. Halaman formal ini merangkum versi 1.0; jika ada perbedaan dengan implementasi atau tampilan lama, spesifikasi kanonik berlaku.</Note></section>

          <section id="model" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Model Penilaian</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3 pr-4">Dimensi</th><th className="py-3 pr-4">Fungsi</th><th className="py-3">Sumber utama</th></tr></thead><tbody>{assessmentDimensions.map((item) => <tr key={item.key} className="border-b border-slate-200 align-top"><td className="py-4 pr-4 font-semibold text-[#0F1E3D]">{item.label}</td><td className="py-4 pr-4">{item.description}</td><td className="py-4 text-slate-500">{item.key === "outcome" ? "Indikator peserta" : item.key === "execution" ? "Habit logs" : item.key === "engagement" ? "Aktivitas program" : item.key === "support" ? "Reminder events" : "Peserta, coach, manager"}</td></tr>)}</tbody></table></div><Note title="Penyajian skor">Kelima dimensi ditampilkan secara terpisah agar hasil, proses, dukungan sosial, dan kekuatan validasi dapat dianalisis secara tepat.</Note></section>

          <section id="self-discovery" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Baseline, Endline & Radar Lima Area</h2><p className="mt-5">Endline Self-Discovery menggunakan 50 butir inti yang sama dengan Baseline. Urutan dapat diacak, tetapi makna, skala, area mapping, dan formula tidak berubah. Pertanyaan refleksi tambahan berada di luar skor inti.</p><Formula>{`Before = Baseline Self-Discovery Area Score\nAfter = Endline Self-Discovery Area Score\nDelta = After - Before`}</Formula><p>Radar lima area hanya membandingkan Baseline dan Endline Self-Discovery. PTP Outcome ditampilkan terpisah karena peserta memilih tiga area dengan indikator personal yang unitnya berbeda.</p><Note title="Waktu Endline">Endline idealnya diisi pada hari ke-85 sampai hari ke-90. Jika belum submitted, Live Report menampilkan "Endline belum tersedia", bukan estimasi.</Note></section>

          <section id="ptp" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Struktur PTP</h2><ol className="mt-5 list-decimal space-y-3 pl-5"><li>Peserta memilih tepat tiga Area Transformasi.</li><li>Setiap area memiliki tepat satu Target Utama 90 Hari miliknya sendiri; target dan indikator tidak disalin lintas area.</li><li>Setiap target menggunakan satu sampai empat indikator aktif.</li><li>Empat jenis indikator eksplisit adalah Kualitas, Kuantitas, Waktu, dan Efisiensi/Biaya. Satu jenis hanya dapat dipakai satu kali dalam area yang sama.</li><li>Setiap indikator wajib memiliki nama, kondisi saat ini dan target 90 hari numerik yang tidak negatif dan berbeda, arah keberhasilan, serta satuan.</li><li>Action plan wajib terhubung ke satu area dan dilacak sebagai habit.</li><li>Area boleh tidak memiliki action plan. Area tersebut berstatus <b>Tidak Diukur</b>, bukan bernilai nol.</li></ol></section>

          <section id="outcome" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Outcome Attainment</h2><p className="mt-5">Outcome membandingkan nilai aktual dengan baseline dan target. Hanya indikator aktif dan terukur yang masuk rata-rata. Headline dibatasi 0-100; gerakan menjauh bernilai minimum 0 dan overachievement maksimum 100.</p><h3 className="mt-6 font-bold text-[#0F1E3D]">Higher is better</h3><Formula>{`Outcome = (Aktual - Baseline) / (Target - Baseline) × 100`}</Formula><h3 className="mt-6 font-bold text-[#0F1E3D]">Lower is better</h3><Formula>{`Outcome = (Baseline - Aktual) / (Baseline - Target) × 100`}</Formula><h3 className="mt-6 font-bold text-[#0F1E3D]">Structural Indicator Coverage</h3><Formula>{`Indicator Coverage = Jumlah indikator aktif / 4 × 100`}</Formula><h3 className="mt-6 font-bold text-[#0F1E3D]">Measurement Coverage</h3><Formula>{`Measurement Coverage = Indikator aktif dengan aktual valid / Jumlah indikator aktif × 100`}</Formula><ul className="mt-4 space-y-2">{["Indikator tidak aktif tidak diberi nilai nol.", "Indikator tanpa aktual mengurangi Measurement Coverage, tetapi tidak masuk rata-rata Outcome.", "Indicator Coverage mengukur luas desain pengukuran.", "Measurement Coverage mengukur kelengkapan data; keduanya bukan kualitas peserta."].map((item) => <li key={item} className="flex gap-2"><Check className="mt-1.5 h-3.5 w-3.5 shrink-0 text-emerald-600" />{item}</li>)}</ul></section>

          <section id="execution" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Behavior Execution</h2><p className="mt-5">Execution mengukur pelaksanaan action plan, bukan hasil target. Denominator hanya menggunakan occurrence yang memang dijadwalkan.</p><Formula>{`Completion per Habit = Selesai / Dijadwalkan × 100`}</Formula><Formula>{`Area Execution = Rata-rata completion setiap habit aktif dalam area`}</Formula><p>Grafik tiga Area Transformasi menggunakan cumulative execution skala 0–100. Occurrence yang tidak dikerjakan bernilai 0 dan menurunkan rata-rata completion melalui denominator.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Frekuensi</th><th className="py-3">Occurrence</th><th className="py-3">Reset</th></tr></thead><tbody><tr className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">Harian</td><td className="py-4">Satu occurrence per hari aktif; quantity adalah unit per hari.</td><td className="py-4 text-slate-500">00.00 zona waktu peserta</td></tr><tr className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">Pekanan</td><td className="py-4">Satu occurrence per minggu; progress dapat ditambah sepanjang minggu.</td><td className="py-4 text-slate-500">Senin 00.00 zona waktu peserta</td></tr><tr className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">Custom</td><td className="py-4">Hanya dihitung jika schedule definition tersedia.</td><td className="py-4 text-slate-500">Sesuai jadwal eksplisit</td></tr></tbody></table></div><Note title="Status implementasi">Dashboard memisahkan kewajiban harian dari progres pekanan. Habit pekanan memiliki satu occurrence per minggu dan tidak masuk daftar habit yang harus selesai pada hari itu.</Note></section>

          <section id="engagement" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Program Engagement</h2><p className="mt-5">Program Engagement bukan Sahabat Safar. Komponen wajib adalah Baseline, PTP, checkpoint matang, dan Core Program Tracking. Journal serta tracker ibadah standalone adalah pengayaan sukarela dan tidak menurunkan kepatuhan.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Komponen</th><th className="py-3">Status</th><th className="py-3">Definisi</th></tr></thead><tbody>{[["Baseline", "Wajib", "Assessment selesai dan submitted"], ["PTP", "Wajib", "3 area, target/indikator valid, dan Action Plan"], ["Checkpoint", "Wajib", "Seluruh checkpoint matang selesai sebelum grace deadline"], ["Core Program Tracking", "Wajib", "Habit tracking dan actual indikator PTP"], ["Journal", "Sukarela", "Metadata aktivitas saja; isi tetap private"], ["Tracker ibadah standalone", "Sukarela", "Statistik pribadi, bukan denominator engagement"]].map(([name, status, definition]) => <tr key={name} className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">{name}</td><td className="py-4">{status}</td><td className="py-4 text-slate-500">{definition}</td></tr>)}</tbody></table></div><Formula>{`Program Participation Index (proposal pilot) =\nBaseline 10% + PTP 20% + Checkpoint 30% + Core Tracking 40%`}</Formula><p>Index belum aktif sebagai metrik resmi sampai denominator checkpoint dan tracking diuji pada minimal satu batch.</p><h3 className="mt-6 font-bold text-[#0F1E3D]">Checkpoint compliance</h3><Formula>{`Grace-adjusted Compliance =\nCheckpoint matang yang disubmit sebelum grace deadline / Seluruh checkpoint matang × 100`}</Formula><p>Checkpoint aktif sejak awal bulan, jatuh tempo pada hari 30/60/90, dan memiliki masa tenggang sampai hari 37/67/97. Checkpoint yang belum matang tidak masuk denominator final.</p><h3 className="mt-6 font-bold text-[#0F1E3D]">Journal dan privasi</h3><p>Journal dianjurkan setiap hari tetapi tetap opsional. Aktivitas dihitung dari jumlah tanggal unik tanpa membaca isi, judul, mood, atau topik. Entry private tidak kehilangan participation credit. Analisis topik tidak dilakukan tanpa opt-in terpisah.</p><h3 className="mt-6 font-bold text-[#0F1E3D]">Core tracking</h3><Formula>{`Core Program Tracking (proposal pilot) =\nHabit Tracking Coverage 70% + Indicator Reporting Compliance 30%`}</Formula><p>Tracker sholat, Al-Qur'an, dan hadits masuk Core Tracking hanya jika menjadi Action Plan PTP. Event yang tersinkron dengan habit dihitung satu kali agar tidak double-count.</p></section>

          <section id="coach" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Penilaian Coach</h2><p className="mt-5">Coach memberikan angka terpisah. Nilai peserta tetap disimpan agar perbedaan penilaian dapat diaudit.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Dimensi</th><th className="py-3">Bobot</th><th className="py-3">Pertanyaan penilaian</th></tr></thead><tbody>{coachAssessmentRubric.map((item) => <tr key={item.label} className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">{item.label}</td><td className="py-4">{item.weight}%</td><td className="py-4 text-slate-500">{item.description}</td></tr>)}</tbody></table></div><Formula>{`Validated Outcome = Participant Outcome × 60% + Coach Assessment × 40%`}</Formula><p>Keempat rubrik coach wajib diisi dengan skor 1-5. Status validasi: Belum Ditinjau, Terverifikasi, Perlu Klarifikasi, atau Tidak Dapat Diverifikasi.</p><p className="mt-3">Manager Evaluation adalah sumber validasi tambahan yang tetap ditampilkan terpisah. Metodologi v1.0 belum memberi bobot manager dalam formula Validated Outcome 60/40.</p></section>

          <section id="support" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Sahabat Safar</h2><p className="mt-5">Reminder Sahabat Safar menjadi metrik Peer Support, bukan Outcome atau Habit Execution. Jumlah individual tidak ditampilkan kepada peserta.</p><Formula>{`Weekly Support Consistency = Minggu dengan dukungan / Minggu pairing aktif × 100`}</Formula><ul className="space-y-2"><li>Satu atau lebih reminder pada minggu yang sama bernilai satu minggu aktif.</li><li>Group Report dapat menampilkan participation, coverage, reciprocal support, dan consistency.</li><li>Pair dan trio menggunakan prinsip yang sama.</li></ul></section>

          <section id="kirkpatrick" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Kirkpatrick Four-Level Funnel</h2><p className="mt-5">Kirkpatrick menggunakan funnel kumulatif. Peserta hanya berada pada Level 3 jika telah memenuhi Level 1, 2, dan 3. Coverage instrumen ditampilkan terpisah dari pass rate.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Level</th><th className="py-3">Instrumen</th><th className="py-3">Proposal lulus</th></tr></thead><tbody>{[["1. Reaction", "Survey akhir 1-5", "Submitted dan rata-rata ≥4/5"], ["2. Learning", "Pre-test dan post-test", "Post ≥70 dan peningkatan ≥10 poin"], ["3. Behavior", "Execution + coach + manager", "Execution ≥70, Manager ≥4/5, coach dapat memverifikasi"], ["4. Results", "Business-linked KPI", "Attainment ≥80% dan VERIFIED"]].map(([level, instrument, pass]) => <tr key={level} className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">{level}</td><td className="py-4">{instrument}</td><td className="py-4 text-slate-500">{pass}</td></tr>)}</tbody></table></div><Formula>{`Level N Rate = Peserta yang lulus seluruh level 1..N / Seluruh peserta eligible × 100`}</Formula><Note title="Status formula">Threshold Kirkpatrick masih proposal sampai pertanyaan Reaction Survey dan Learning Test disetujui.</Note></section>

          <section id="business" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Business Impact & ROI</h2><p className="mt-5">Tidak semua target PTP dipaksa menjadi target perusahaan. Target profesional yang relevan dapat ditandai Business-linked dan harus disetujui manager sebelum masuk Business Impact.</p><ol className="mt-4 list-decimal space-y-2 pl-5"><li>Peserta mengusulkan KPI, baseline, target, dan sumber data.</li><li>Manager menyetujui relevansi dan mengunci definisi.</li><li>Peserta mengisi actual dan evidence.</li><li>Manager dan Business Owner memvalidasi dampak.</li><li>Finance memvalidasi nilai finansial untuk ROI.</li></ol><Formula>{`Verified Program Benefit = Gross Monetary Benefit × Attribution Percentage\nNet Program Benefit = Verified Program Benefit - Total Program Cost\nROI = Net Program Benefit / Total Program Cost × 100`}</Formula><p>Jika Finance belum memverifikasi benefit atau cost, ROI berstatus Belum Terverifikasi dan tidak ditampilkan sebagai angka live.</p></section>

          <section id="readiness" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Leadership Readiness Index</h2><p className="mt-5">Readiness mengukur kesiapan peserta memimpin, menjadi teladan, dan menularkan praktik baik kepada bawahan.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Dimensi</th><th className="py-3">Bobot</th></tr></thead><tbody>{[["Self-leadership dan integritas", "20%"], ["Role modelling", "25%"], ["Coaching dan pengembangan bawahan", "25%"], ["Akuntabilitas dan penerapan", "15%"], ["Keberlanjutan perubahan", "15%"]].map(([dimension, weight]) => <tr key={dimension} className="border-b border-slate-200"><td className="py-4 font-semibold text-[#0F1E3D]">{dimension}</td><td className="py-4">{weight}</td></tr>)}</tbody></table></div><Formula>{`Readiness Index (proposal pilot) =\nManager 50% + Coach 30% + Participant Self 20%`}</Formula><p>Semua sumber wajib tersedia. Jika manager belum mengisi, statusnya Readiness belum terverifikasi. Bobot dan threshold harus diuji pada satu atau dua batch sebelum menjadi metodologi resmi.</p></section>

          <section id="report" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Group Impact Report</h2><p className="mt-5">Setiap metrik agregat menampilkan denominator, jumlah responden terukur, coverage, versi metodologi, dan cutoff data agar hasil dapat diinterpretasikan secara akurat. Nilai null tidak diubah menjadi nol.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Bagian</th><th className="py-3">Metrik</th></tr></thead><tbody>{[["Self-Discovery", "Baseline, Endline, dan delta lima area"], ["Transformation Outcomes", "Participant Outcome, Indicator Coverage, Measurement Coverage, Coach Assessment, Validated Outcome"], ["Behavior Execution", "Habit completion per area dan monthly trend"], ["Program Participation", "Baseline, PTP, checkpoint, Core Tracking; journal sukarela terpisah"], ["Peer Support", "Weekly consistency, coverage, reciprocal support"], ["Validation", "Coach coverage dan manager coverage terpisah"], ["Kirkpatrick", "Reaction, Learning, Behavior, Results sebagai funnel kumulatif"], ["Business", "Verified KPI, monetary benefit, ROI verification"], ["Readiness", "Multi-source leadership readiness"]].map(([area, metric]) => <tr key={area} className="border-b border-slate-200"><td className="py-4 pr-4 font-semibold text-[#0F1E3D]">{area}</td><td className="py-4 text-slate-500">{metric}</td></tr>)}</tbody></table></div><Note title="Status metrik live">Outcome, Execution, Peer Support, dan Coach Validation memiliki formula v1.0. Program Participation, Kirkpatrick, Business Impact, ROI, dan Readiness disiapkan sebagai instrumen/versioned workflow; angka live baru ditampilkan setelah instrumen, coverage, dan validator tersedia.</Note></section>

          <section id="interpretation" className="scroll-mt-24"><h2 className="border-b border-slate-200 pb-3 text-xl font-bold text-[#0F1E3D]">Interpretasi Outcome × Execution</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-300 text-xs text-slate-500"><th className="py-3">Outcome</th><th className="py-3">Execution</th><th className="py-3">Interpretasi</th></tr></thead><tbody>{[["Tinggi", "Tinggi", "Perubahan berjalan dan memberi hasil."], ["Rendah", "Tinggi", "Evaluasi efektivitas action plan."], ["Tinggi", "Rendah", "Validasi sumber perubahan."], ["Rendah", "Rendah", "Perlu intervensi coach."]].map((row) => <tr key={row.join()} className="border-b border-slate-200">{row.map((cell, index) => <td key={`${index}-${cell}`} className={`py-4 pr-4 ${index < 2 ? "font-semibold text-[#0F1E3D]" : "text-slate-500"}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>
        </article>

        <aside className="hidden xl:block"><div className="sticky top-24 border-l border-slate-200 pl-5 text-xs leading-6 text-slate-500"><p className="font-bold uppercase tracking-wide text-slate-400">On this page</p><p className="mt-3">Owner: BinaJourney Program Team</p><p>Audience: Admin, Coach, Management</p><p>Version: {METHODOLOGY_VERSION}</p><a href="/admin/report" className="mt-4 inline-block font-semibold text-[#9A762C] hover:text-[#0F1E3D]">Open Impact Report →</a></div></aside>
      </div>
    </div>
  );
}
